#define SLEEPMODE_ENABLE

// #define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_REACTIVE
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 250 /* The maximum brightness level */
#define RGB_MATRIX_STARTUP_VAL 150
#define RGB_MATRIX_STARTUP_HUE 130
#define RGB_MATRIX_STARTUP_SAT 180
#define RGB_MATRIX_KEYPRESSES
//#define RGBLIGHT_SLEEP  /* If defined, the RGB lighting will be switched off when the host goes to sleep */
// #define RGBLIGHT_HUE_STEP 8
// #define RGBLIGHT_SAT_STEP 8
// #define RGBLIGHT_VAL_STEP 8
/*== all animations enable ==*/
#define RGBLIGHT_ANIMATIONS
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
// /*== or choose animations ==*/
// #define RGBLIGHT_EFFECT_BREATHING
// #define RGBLIGHT_EFFECT_RAINBOW_MOOD
// #define RGBLIGHT_EFFECT_RAINBOW_SWIRL
// #define RGBLIGHT_EFFECT_SNAKE
// #define RGBLIGHT_EFFECT_KNIGHT
// #define RGBLIGHT_EFFECT_CHRISTMAS
// #define RGBLIGHT_EFFECT_STATIC_GRADIENT
// #define RGBLIGHT_EFFECT_RGB_TEST
// #define RGBLIGHT_EFFECT_ALTERNATING
